### ISSUE TITLE
slurm RPC count

### ISSUE THREAD

**Issue by frankrwth** [rwth-i6/sisyphus#108]
Dear sisyphus developers,

I noticed that some HPC users using the sisyphus engine are performing a large amount of Slurm RPCs (squeue) at once on the RWTH HPC Cluster.
At large scales this can cause issues for the **slurmctld**, where the daemon hangs and the stability of the system is endangered.
Would it be possible to have `sisyphus/engine.py` changed, so that there is a delay (configurable to the user if you wish) between calls of `self.task_state(task)`, instead of the current uncapped for loop (there is currently no throttling).
This function calls **squeue** in the background  if I understand correctly. 
When Slurm commands are called in an automated fashion, the **slurmctld** will have issues handling uncapped RPCs (This is an issue of Slurm/SchedMD). 
A delay of 3 to 5 seconds is preferred (perhaps configurable for the user).
Example:
```
       for task in job._sis_tasks():
            if not task.finished():
                time.sleep(5.0)
                return self.task_state(task)
```

Or alternatively have self.task_state(task) check all ids at once with a single squeue call?
This is a very important change that would help us maintain a good uptime on the slurmctld.
This would also avoid us having to **warn** every user using your engine.

Thank you for your help on this matter.

**Comment by michelwi** [comment]
Thanks for bringing this to our attention.

The problematic call to to squeue happens in the `queue_state` function, that already caches the results and _should_ only issue a new request every 30 seconds.
https://github.com/rwth-i6/sisyphus/blob/5e8468dcccd7b8800efa646311fb1b4111b1c755/sisyphus/simple_linux_utility_for_resource_management_engine.py#L264-L269

Can you confirm that the Slurm RPCs come from squeue calls or could it be that some user is submitting a large amount of jobs at the same time and that the requests are actually sbatch calls instead?

**Comment by frankrwth** [comment]
Thank you for the clarification!
It was my mistake, the code clearly already delays it.
I will keep an eye out for the users next time and see if it was sbatch or a user external custom squeue loop.
sbatch should not be an issue, although at large scales job arrays are desired.
Thank you again for the quick reply. This can be closed 👍
