### ISSUE TITLE
update_engine_rqmt in settings can not be pickled

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#112]
I defined a `update_engine_rqmt` function in my `settings.py`, which is in the root of my setup.
Now I get this pickling error:
```
...
  File "/u/zeyer/setups/combined/2021-05-31/tools/sisyphus/sisyphus/manager.py", line 406, in Manager.run_jobs.<locals>.f
    line: job._sis_setup_directory() 
    locals: 
      job = <local> Job<work/i6_core/returnn/search/ReturnnSearchJobV2.ooVjHv7YzCd9> 
      job._sis_setup_directory = <local> <bound method Job._sis_setup_directory of Job<work/i6_core/returnn/search/ReturnnSearchJobV2.ooVjHv7YzCd9>> 
  File "/u/zeyer/setups/combined/2021-05-31/tools/sisyphus/sisyphus/job.py", line 290, in Job._sis_setup_directory 
    line: pickle.dump(self, f) 
    locals: 
      pickle = <global> <module 'pickle' from '/work/tools/asr/python/3.8.0/lib/python3.8/pickle.py'> 
      pickle.dump = <global> <built-in function dump> 
      self = <local> Job<work/i6_core/returnn/search/ReturnnSearchJobV2.ooVjHv7YzCd9> 
      f = <local> <gzip on 0x7fbcdc4bd190> 
PicklingError: Can't pickle <function update_engine_rqmt at 0x7fbcde8b90d0>: import of module 'settings.py' failed 
```

This is because `update_global_settings_from_file` and `update_global_settings_from_text` do not properly import the module but instead manually do `compile` and `exec`. Esp, the `__name__` for the module exec globals is set incorrectly. Otherwise I think it might have worked already (for the case of `settings.py` in the root dir, at least).

I wonder, is setting `update_engine_rqmt` in the user settings not supported? Or how would that work?

And also, should we maybe fix `update_global_settings_from_text` a bit, that it would at least set `__name__` correctly for this case?

**Comment by albertz** [comment]
> Otherwise I think it might have worked already (for the case of `settings.py` in the root dir, at least).

Ok, this is not enough. It is further a problem that there is no module in `sys.modules` with this name. You could also somehow hack around that. E.g. this code inside my `settings.py` makes it work:
```python

import os
import sys

_root_dir = os.path.dirname(os.path.abspath(__file__))

# https://github.com/rwth-i6/sisyphus/issues/112
__name__ = "settings"
sys.path.append(_root_dir)
class _Mod:
  def __init__(self):
    self.__dict__ = globals()
sys.modules[__name__] = _Mod()
```

However, I wonder, why not just directly use `importlib`? Ok, this will not work for setting files which are not easily directly importable. But otherwise, this is probably a cleaner way.

**Comment by JackTemaki** [comment]
> I wonder, is setting `update_engine_rqmt` in the user settings not supported? Or how would that work?

It was always supported, and never caused a problem for me. Not sure what is different in your case.

**Comment by albertz** [comment]
> It was always supported, and never caused a problem for me.

But how? It is set as the `_update_rqmt` attrib to the `Task` instance. The `Job` instance gets pickled, and I assume it must somehow have a reference to the tasks. So how can this pickling work for you?

Maybe the `Job.update` is related? Without `Job.update`, maybe in your case, the `Job` does not have references to `Task` objects?

There is `Job._sis_task_cache`, which is included in `Job.__getstate__`.

**Comment by critias** [comment]
If I get this right you define `update_engine_rqmt` function inside the `settings.py` which is later passed to a `Task`. While pickling a job it also tries to pickle all tasks and fail doing so.

Importing `settings.py` like this was not a problem so far, so there was no need to change it. It might be possible to switch to importlib.

What are you trying to do that your Task need the `update_engine_rqmt` function? Did you try to use `from sisyphus.global_settings import update_engine_rqmt` when you need that function?

**Comment by albertz** [comment]
> you define `update_engine_rqmt` function inside the `settings.py`

Yes. Is this not intended to be done? You sound like you think I do sth unexpected here?


> which is later passed to a `Task` ...

I mean, these are implementation details of Sisyphus. I don't do that explicitly. This is done by Sisyphus internally.


> What are you trying to do that your Task need the `update_engine_rqmt` function?

If I don't define it, it would use the default `sisyphus.global_settings.update_engine_rqmt`, right? But I don't like the default `update_engine_rqmt` because it increases the memory requirements, and I don't want that.

**Comment by critias** [comment]
Fixed by https://github.com/rwth-i6/sisyphus/pull/113
