### ISSUE TITLE
Better manager logging

### ISSUE THREAD

**Issue by Icemole** [rwth-i6/sisyphus#136]
Hi all! When I work with sisyphus, I usually work with many interdependencies between files and functions, and my manager usually interprets jobs that are on average two to three calls below the main configuration file. As a result, trying to see which job failed, as well as the code surrounding the failing job, is a frustrating task since sisyphus doesn't provide a stack trace of where the fail is, as opposed to running the bare setup.

I thought of this, and I came to the conclusion that I could probably debug faster if I got at least the path and line which made my job break. For instance, instead of what we have currently:

```
[2023-06-08 13:22:20,259] ERROR: error: Job<job-dir>
```

I think logging the information as follows would be much more efficient for the programmer:

```
[2023-06-08 13:22:20,259] ERROR: Job<job-dir> (<py-that-defines-job>:<specific-line>)
```

I don't know if this is already implemented, but I checked sisyphus's help and found nothing related, only `log_level`. My question would be: is this implemented? And if not, would it be much effort to implement?

**Comment by critias** [comment]
Did you set `PRINT_ERROR = False`? It should be enabled by default and print out parts of the log file which provide more informations why the job crashed: 
https://github.com/rwth-i6/sisyphus/blob/master/sisyphus/global_settings.py#L202

Or are you looking for a traceback where the job was created? I haven't done it in a while, but if you set `JOB_ADD_STACKTRACE_WITH_DEPTH = -1` it should store the whole traceback and write it into the info file of the job:
https://github.com/rwth-i6/sisyphus/blob/master/sisyphus/global_settings.py#L273

**Comment by Icemole** [comment]
Thank you for commenting. I tested the flags that you mention, and while they're fine for additional logging, my specific issue isn't to know how the job crashed, as I can easily check it by going to the respective directory inside `work/`. My aim involves knowing instantly the place where the job was spawned, or in other words, where the job that crashes was actually instantiated. Would it be possible to know that by some flag that's already developed in sisyphus?

**Comment by Icemole** [comment]
`JOB_ADD_STACKTRACE_WITH_DEPTH` seems to be what I was looking for! Thank you!!

**Comment by critias** [comment]
Just for your information: It's not enabled by default since it slows down the job creation quite a bit. This can cause a significant slow down when starting sisyphus with a large workflow.

**Comment by Icemole** [comment]
Thank you for the additional information, it will be kept in mind :)

**Comment by Icemole** [comment]
Does setting a low value of the variable, like `1`, help speed up things when loading the setup? Or is it the fact that the variable is different from `0` which is what triggers the slow workflow?

**Comment by critias** [comment]
The value here doesn't matter for speed. Extracting the traceback is the expensive part no matter how much is saved in the end.

**Comment by Icemole** [comment]
When setting the value to `-1`, I get the following error:

```
File /usr/local/lib/python3.10/dist-packages/sisyphus/job.py:133, in JobSingleton.__call__(cls=<class 'i6_core.tools.git.CloneGitRepositoryJob'>, *args=(), **kwargs={'commit': 'c671657d46d9c3d475c3a4854a8f06b34af7f548', 'url': 'https://github.com/rwth-i6/returnn.git'})
    131 # add stacktrace information, if set to None or -1 use full stack
    132 stack_depth = gs.JOB_ADD_STACKTRACE_WITH_DEPTH + 1 if gs.JOB_ADD_STACKTRACE_WITH_DEPTH >= 0 else None
--> 133 if stack_depth > 1 or None:
        stack_depth = None
    134     # add +1 for the traceback command itself, and remove it later
    135     stacktrace = traceback.extract_stack(limit=stack_depth)[:-1]
    136     job._sis_stacktrace.append(stacktrace)

TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Probably a more suitable conditional would be `if stack_depth is not None or stack_depth > 1`? Actually I believe that conditional statement is equivalent to `if stack_depth > 1`, since `or None` always evaluates to `False`.

**Comment by critias** [comment]
Looks like this line should be:
`if stack_depth is None or stack_depth > 1:`
Could try it and setup a PR?
