### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#138]
Do we want to enforce black here, just like in most other i6 repos? Same settings, 120 char line limit?

**Comment by critias** [comment]
I like these kind of tools, but would leave the decision up to people that are currently actively working on Sisyphus (which excludes me).
What are the settings used in the other i6 repos?

**Comment by albertz** [comment]
120 char line limit, that's all.

**Comment by albertz** [comment]
@curufinwe @michelwi @vieting @JackTemaki or who else?

**Comment by JackTemaki** [comment]
Ok for me

**Comment by michelwi** [comment]
I like black in general. +1 from my side.
