### ISSUE TITLE
Log file for finished output

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#152]
I often would miss the "Finished output: ..." log message by the Sis manager on stdout, as it usually prints quite a lot when there are a few experiments running.

A log file with those (human readable timestamp + what output was finished) would be very useful.

I assume this would need to be implemented. So this is a feature request. Maybe you could also suggest already a place where and how to implement it, so then I could also do a PR myself.

**Comment by critias** [comment]
This should be an easy to add, just add it to the place where the log message is trigged:
https://github.com/rwth-i6/sisyphus/blob/master/sisyphus/graph.py#L114C26-L114C26

**Comment by albertz** [comment]
Do we have other log files already?

Or would this be some option in global settings, like `finished_output_log_filename: Optional[str] = None` or so, and if that is set, then we would add this code here:
```python
if gs.finished_output_log_filename:
  with open(gs.finished_output_log_filename, "a") as f:
    f.write(datetime.now().strftime("%Y-%m-%d %H:%M:%S: ") + f"Finished output: {outfile_name}\n")
```

**Comment by critias** [comment]
All log files I can think of are used by workers and not by the manger.
There might be a nice solution with the logging module, but I don't know it well enough. Considering that we currently only want to log this one thing I think your solution looks good.
