### ISSUE TITLE
`sis_hash_helper` on `enum.Enum`s is Python version dependent

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#188]
The use of `enum.Enum` currently results in different Sisyphus hashes depending on the Python version…

E.g. from i6_core, we have:
```python
class MergeStrategy(enum.Enum):
    SUBCORPORA = 0
    FLAT = 1
    CONCATENATE = 2
```

`sis_hash_helper(MergeStrategy.FLAT)` gives:
* Python 3.11: `b"(MergeStrategy, (dict, (tuple, (str, '__objclass__'), (EnumType, (tuple, (str, 'i6_core.corpus.transform'), (str, 'MergeStrategy')))), (tuple, (str, '_name_'), (str, 'FLAT')), (tuple, (str, '_sort_order_'), (int, 1)), (tuple, (str, '_value_'), (int, 1))))"`
* Python 3.10: `b"(MergeStrategy, (dict, (tuple, (str, '__objclass__'), (EnumMeta, (tuple, (str, 'i6_core.corpus.transform'), (str, 'MergeStrategy')))), (tuple, (str, '_name_'), (str, 'FLAT')), (tuple, (str, '_value_'), (int, 1))))"`

I think most people still use Python <=3.10? Am i the only one using a more recent Python? I would suggest a fix on Sisyphus side to always keep the old python <=3.10 hash of `enum`, even on newer Python versions. That will require a special check for `enum`, but I think that’s ok.

**Comment by michelwi** [comment]
> Am i the only one using a more recent Python?

It seems so.

> suggest a fix on Sisyphus side to always keep the old python <=3.10 hash of enum

yes, agreed.

**Comment by critias** [comment]
I didn't expect the enum state to blow up like that. There would also be the option to encode it into something shorter, e.g. b'(Enum, i6_core.corpus.transform. MergeStrategy.Flat)', but that would now change the hash. Keeping the old behavior looks reasonable to me.
