### ISSUE TITLE
Incorrect type annotations for rqmt in task.py

### ISSUE THREAD

**Issue by jtrmal** [rwth-i6/sisyphus#197]
Seems to me (and to my editor) it shouldn't be
`rqmt: dict[str]`
but
`rqmt: Optional[typing.Dict[str, Any]]`
(since typically  you have None as a default value )
Can you plz confirm if you care about me submitting a PR or not? Thanks!

**Comment by JackTemaki** [comment]
Can confirm! I think for docstrings you simply write `dict[str, Any] | None` though...

**Comment by michelwi** [comment]
yes pls, PR welcome.

**Comment by jtrmal** [comment]
Seems like this has been resolved in the master last week(?), closing. Apologies for the noise.
