### ISSUE TITLE
Error in cleaner: sis_graph.targets set changed size during iteration 

### ISSUE THREAD

**Issue by ArneNx** [rwth-i6/sisyphus#22]
Since updating to the current master (from a version in November), I recently get the error message below, when I try to run the cleaner. 
I have no sisyphus sessions running anywhere, so I think this is very odd. 
```
In [1]: tk.cleaner(clean_job_dir=True, clean_work_dir=True, mode='remove')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-7338018b81e2> in <module>()
----> 1 tk.cleaner(clean_job_dir=True, clean_work_dir=True, mode='remove')

~/src/sisyphus/sisyphus/toolkit.py in cleaner(clean_job_dir, clean_work_dir, mode, keep_value, only_remove_current_graph)
    446     # the output of unfinished jobs or belong to the output
    447     needed = set()
--> 448     for target in sis_graph.targets:
    449         for path in target.required:
    450             active_paths[os.path.abspath(os.path.join(path.get_path()))] = path

RuntimeError: Set changed size during iteration
```

I don't have time to investigate this right now, so I was wondering if anyone has seen this before or has any idea what could cause this.

**Comment by critias** [comment]
Ich hab ne Vermutung, versuch mal:
for target in sis_graph.targets
in 
for target in sis_graph.targets.copy()
zu ändern.

Schau ich mir später nochmal genauer an.

/jtp

**Comment by ArneNx** [comment]
Mist, da hätte ich auch selber drauf kommen können.
Das schein zu funktionieren.

**Comment by critias** [comment]
Oh, I thought I answered to your regular email and forgot to push the update... Well, it's fixed now.
