### ISSUE TITLE
Structuring the output directory?

### ISSUE THREAD

**Issue by ibenes** [rwth-i6/sisyphus#34]
Dear maintainers,
I remember that when I was running Sisyphus during my stay at i6, the outputs were structured by the respective config, e.g. `output/01_gmm/wer.txt`. When I run vanilla Sisyphus (+customized engine) at our lab, this does not happen, i.e. I'd get `output/wer.txt`.

Is there some flag (which I perhaps just copied from someone's settings, oblivious to its effect) to achieve the structuring?

**Comment by critias** [comment]
I guess the setups you used at i6 included a line where it added a prefix for the output directory in the config file, something like:
tk.gs.ALIAS_AND_OUTPUT_SUBDIR = '01_gmm'
or
tk.gs.ALIAS_AND_OUTPUT_SUBDIR = __name__

https://sisyphus-workflow-manager.readthedocs.io/en/latest/#sisyphus.global_settings.ALIAS_AND_OUTPUT_SUBDIR

Be aware that if you set it, it will be enabled for all outputs that are added afterwards, even if the are inside a different config file. Does that solve your problem?

**Comment by ibenes** [comment]
It did the trick. Special thanks for the `__name__` hint!
