### ISSUE TITLE
config file not loaded correctly

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/sisyphus#36]
Hi,
I have a problem with the naming of config files. It used to be the way that all filenames where allowed. But now they are limited to names which are valid python modules.
This breaks my setup since I use numbers in the file name beginning and use periods and hyphens.

`` ./sis --config 01_test.py m ``

> [2020-03-13 17:19:58,740] ERROR: Main thread unhandled exception:
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> ~/dev/sisyphus_2020-03-13/sisyphus/__main__.py in main()
>     204             t.join()
>     205         else:
> --> 206             args.func(args)
>         args.func = <function manager at 0x7f24078134c0>
>         args = Namespace(argv=[], clear_errors_once=False, clear_interrupts_once=False, config_files=['01_test.py'], filesystem=None, func=<function manager at 0x7f24078134c0>, http_port=None, ignore_once=False, interactive=False, log_level=20, run=False, ui=False)
>     207     except BaseException as exc:
>     208         if not isinstance(exc, SystemExit):
> 
> ~/dev/sisyphus_2020-03-13/sisyphus/manager.py in manager(args=Namespace(argv=[], clear_errors_once=False, clea...ractive=False, log_level=20, run=False, ui=False))
>      70 
>      71     start = time.time()
> ---> 72     load_configs(args.config_files)
>         global load_configs = <function load_configs at 0x7f24083e0700>
>         args.config_files = ['01_test.py']
>      73     load_time = time.time() - start
>      74     if load_time < 5:
> 
> ~/dev/sisyphus_2020-03-13/sisyphus/loader.py in load_configs(filenames=['01_test.py'])
>      80 
>      81     for filename in filenames:
> ---> 82         load_config_file(filename)
>         global load_config_file = <function load_config_file at 0x7f24083e0670>
>         filename = '01_test.py'
>      83 
>      84 
> 
> ~/dev/sisyphus_2020-03-13/sisyphus/loader.py in load_config_file(config_name='01_test.py')
>      25 
>      26     filename = filename.replace(os.path.sep, '.')  # allows to use tab completion for file selection
> ---> 27     assert all(part.isidentifier() for part in filename.split('.')), "Config name is invalid: %s" % filename
>         global all = undefined
>         global part.isidentifier = undefined
>         global part = undefined
>         filename.split = <built-in method split of str object at 0x7f240d6c11f0>
>         filename = '01_test.py'
>      28     module_name, function_name = filename.rsplit('.', 1)
>      29     try:
> 
> AssertionError: Config name is invalid: 01_test.py

`./sis --config tttt.py m `

> [2020-03-13 18:45:42,605] ERROR: Main thread unhandled exception:
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> ~/dev/sisyphus_2020-03-13/sisyphus/__main__.py in main()
>     204             t.join()
>     205         else:
> --> 206             args.func(args)
>         args.func = <function manager at 0x7f0ba4f09550>
>         args = Namespace(argv=[], clear_errors_once=False, clear_interrupts_once=False, config_files=['tttt.py'], filesystem=None, func=<function manager at 0x7f0ba4f09550>, http_port=None, ignore_once=False, interactive=False, log_level=20, run=False, ui=False)
>     207     except BaseException as exc:
>     208         if not isinstance(exc, SystemExit):
> 
> ~/dev/sisyphus_2020-03-13/sisyphus/manager.py in manager(args=Namespace(argv=[], clear_errors_once=False, clea...ractive=False, log_level=20, run=False, ui=False))
>      70 
>      71     start = time.time()
> ---> 72     load_configs(args.config_files)
>         global load_configs = <function load_configs at 0x7f0ba5223c10>
>         args.config_files = ['tttt.py']
>      73     load_time = time.time() - start
>      74     if load_time < 5:
> 
> ~/dev/sisyphus_2020-03-13/sisyphus/loader.py in load_configs(filenames=['tttt.py'])
>      85 
>      86     for filename in filenames:
> ---> 87         load_config_file(filename)
>         global load_config_file = <function load_config_file at 0x7f0ba526e550>
>         filename = 'tttt.py'
>      88 
>      89 
> 
> ~/dev/sisyphus_2020-03-13/sisyphus/loader.py in load_config_file(config_name='tttt.py')
>      33     try:
>      34         print(module_name, function_name)
> ---> 35         config = importlib.import_module(module_name)
>         config = undefined
>         global importlib.import_module = <function import_module at 0x7f0baaf054c0>
>         module_name = 'tttt'
>      36     except SyntaxError:
>      37         import sys
> 
> /work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/lib/python3.8/importlib/__init__.py in import_module(name='tttt', package=None)
>     125                 break
>     126             level += 1
> --> 127     return _bootstrap._gcd_import(name[level:], package, level)
>         global _bootstrap._gcd_import = <function _gcd_import at 0x7f0bab00d430>
>         name = 'tttt'
>         level = 0
>         package = None
>     128 
>     129 
> 
> /work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name='tttt', package=None, level=0)
> 
> /work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name='tttt', import_=<function _gcd_import>)
> 
> /work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name='tttt', import_=<function _gcd_import>)
> 
> ModuleNotFoundError: No module named 'tttt'

`./sis --config test.py m`

> [2020-03-13 17:24:40,466] INFO: Loaded config: test.py
> [2020-03-13 17:24:40,526] INFO: Experiment directory: /u/luescher/setups/punctuation-prediction/2019-07-29--iwslt-paper      Call: /u/luescher/dev/sisyphus_2020-03-13/sis --config test.py m
> Print verbose overview (v), update aliases and outputs (u), start manager (y), or exit (n)? n
> [2020-03-13 17:24:44,375] INFO: Manager loop stopped

`./sis --config config.py m `

> [2020-03-13 17:25:55,969] INFO: Loaded config: config.py
> [2020-03-13 17:25:55,969] INFO: Config loaded (time needed: 6.11)
> [2020-03-13 17:25:56,435] INFO: Experiment directory: /u/luescher/setups/punctuation-prediction/2019-07-29--iwslt-paper      Call: /u/luescher/dev/sisyphus_2020-03-13/sis --config config.py m
> [2020-03-13 17:25:56,437] INFO: runnable: Job<work/corpus/CorpusToStm.S1yirGGByxOE> [Extract STM from Corpus]

This is all the same config. This behavior does not concern files that are located in recipes. I would like to start single config files which are located at the top-level and not only the config.py. Is it possible to get the old behavior back?

**Comment by critias** [comment]
This is related to switching from loading the config with importlib instead of the hack exec/compile method I used before: https://github.com/rwth-i6/sisyphus/commit/2fd7b9f6cda5110cad413128a235071fa20ecfa4

A side effect of this is that all config files need to be either in the config (the right place) or recipe (the wrong place) directory to be found. The files name must also be a valid identifier.
test.py does not throw an exception, but also doesn't add any jobs, since there is already module named test in python which is loaded. config.py works since we add the config as possible place for modules.

Is there any reason why putting your config files under config/ does not work for you?
Otherwise I would just add a check that all config files must start with config/ and will also mention this format in the error message if a invalid filename is used.

**Comment by christophmluscher** [comment]
Yes, that commit changes the behavior.

I will adapt my setup. This is probably the cleaner solution :)
