### ISSUE TITLE
Mark job as "create but do not execute"

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/sisyphus#39]
This is more a feature request than an issue. I thought about the case that I often want to run my jobs until I reach a specific job, where I want to manually check all inputs/code etc. until actual execution. Also sometimes I want to delete broken jobs, but do not directly run them again, but also keeping them in the graph. 

So what do you think about having a kind of "job.wait()" function, that will add a "wait" file in the Job folder marking, that the Job should be created but no task should run yet? Am I the only one that would be using this?

**Comment by critias** [comment]
I agree that this is a good idea and will look into it. I thought about adding a 'hold' function a while ago, but it didn't bother me enough to implement anything at the time.

**Comment by critias** [comment]
This commit should add this functionality:
https://github.com/rwth-i6/sisyphus/commit/917306979b21598865a9cdf3fdc6d1ebb0d9f147

You can now either call job.hold() or add a file named `hold` into the job directory to not start the job, but let sisyphus create the work directory if it doesn't exist yet.
