### ISSUE TITLE
Asserting manager vs worker

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/sisyphus#55]
Is there an intended way in Sisyphus to check if code is run via the manager or via the worker? I would like to add some `assert` calls to specific code parts that should never be called from the manager, but only from inside jobs.

**Comment by critias** [comment]
There is currently no marker that can simply checked. Would this here work for you: https://github.com/rwth-i6/sisyphus/pull/56 ?

**Comment by critias** [comment]
Resolved with https://github.com/rwth-i6/sisyphus/pull/56
