### ISSUE TITLE
Input path checking

### ISSUE THREAD

**Issue by curufinwe** [rwth-i6/sisyphus#67]
After line https://github.com/rwth-i6/sisyphus/blob/acebc54712037239e3f05b43ddd52cc1be5b6a5a/sisyphus/graph.py#L461 there is some code to check if a Path exists, shouldn't this be a call to https://github.com/rwth-i6/sisyphus/blob/acebc54712037239e3f05b43ddd52cc1be5b6a5a/sisyphus/job_path.py#L128 ?

**Comment by critias** [comment]
This code is only looking for path without a creator, so line 461 needs to stay, but the next two lines could be replaced with a call to `path.available()`.
