### ISSUE TITLE
Inconsistencies in memory specification

### ISSUE THREAD

**Issue by jan-rosendahl** [rwth-i6/sisyphus#7]
In class Task memory is sometimes stored as int and sometimes as string (e.g. '2G'). This can cause problems when an old memory value is read or compared to a new one. In the case of update_rqmt: 

https://github.com/rwth-i6/sisyphus/blob/4693518bfee47a96f1f4c01e928a4385ebe72a9d/sisyphus/task.py#L402-L417

for initial_rqmt mem is converted to an int, but the file on disk can be in string format still. `tools.str_to_GB` should be called either on `last_usage` or possibly directly on `self._rqmt` directly.

**Comment by critias** [comment]
I did both. Updating it at the beginning is cleaner, but old jobs might still have strings stored in their usage file.
