### ISSUE TITLE
Manager does not stop if there are interrupted jobs without a resume function

### ISSUE THREAD

**Issue by curufinwe** [rwth-i6/sisyphus#72]
Currently the manager does not terminate if there are still interrupted jobs. This is OK as we might be able to resubmit those. But when when those jobs don't have the resume function set the manager still remains running. In my particular setup I don't want the jobs to be resubmitted as they are part of an automated testing-pipeline and failure to finish in the allotted time is a bug that I want to be able to catch.

@critias do you have time to look into this? Thank!

**Comment by critias** [comment]
I think the best way to solve it is to create a new state like `non_resumable_interrupted` that also makes it clear if I a running manager will resume an interrupted job or not. I'll take a look at it.
