### ISSUE TITLE
Sisyphus console cleanup also tries to cleanup .history files

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/sisyphus#76]
Using e.g.
```
used = tk.cleaner.list_all_graph_directories()
unused = tk.cleaner.search_for_unused(used)
tk.cleaner.remove_directories(unused, "test", mode="move")
```
in the console also moves files like .history.hilmes

**Comment by critias** [comment]
Well, the idea behind search_for_unused is to delete everything that doesn't belong into the work folder. So this behavior is expected. It would be possible to add an optional check that only job directories are removed (or just moved). Would that work for you?

**Comment by Atticus1806** [comment]
I see. Yes that would work. But its not a high priority just wanted to report what I saw, if you say its intended then its fine too.
