### ISSUE TITLE
worker_helper removes worker_wrapper on localengine

### ISSUE THREAD

**Issue by michelwi** [rwth-i6/sisyphus#78]
I use (on bare metal) a virtualenv to run sisyphus. Then I use a worker_wrapper function to run some tasks with a singularity image. Here the virtualenv does not exist any more but the default python within the image has all required modules.

original call:
```
['/path/to/virtualenv/bin/python', '/home/wmichel/software/sisyphus/sis', 'worker', 'work/path/to/MyJob.a0OOf4GEhHZ8', 'my_task']
```
after worker_wrapper:
```
['singularity', 'run', '/path/to/singularity_image.sif', 'python3', '/home/wmichel/software/sisyphus/sis', 'worker', 'work/path/to/MyJob.a0OOf4GEhHZ8', 'my_task']
```

now the Task `my_task` task is a mini_task i.e. the local engine is used. 
The manager finds the runnable task 
```
DEBUG: Found new task: TaskQueueInstance(call=['singularity', 'run', '/path/to/singularity_image.sif', 'python3', '/home/wmichel/software/sisyphus/sis', 'worker', '--engine', 'short', 'work/path/to/MyJob.a0OOf4GEhHZ8', 'my_task', '1', '--redirect_output'], logpath='work/path/to/MyJob.a0OOf4GEhHZ8/engine', rqmt={'cpu': 1, 'mem': 1.0, 'time': 1.0, 'engine': 'short', 'engine_info': 'my_pc.local', 'engine_name': 'local'}, name='path/to/MyJob.a0OOf4GEhHZ8.my_task', task_name='my_task', task_id=1)
```

But then after the lines https://github.com/rwth-i6/sisyphus/blob/5f1373a0da21c8189ac316a60dea83a926bd2584/sisyphus/worker.py#L186-L189
the wrapped singularity call is reset to the original
```
['/path/to/virtualenv/bin/python', '/home/wmichel/software/sisyphus/sis', 'worker', '--engine', 'short', 'work/path/to/MyJob.a0OOf4GEhHZ8/engine', 'my_task', '1']
```
which fails, as the task requires the singularity image.

So.. are these lines needed? Can we remove them or add another worker_wrapper call?

**Comment by critias** [comment]
I ran into some edge cases were not doing this caused a problem, but I'm not sure any more which case it was. Most likely if sisyphus was run as part of an external script, but I don't see why this should be a problem anymore.
I really should have added a comment here 😄 

For now: Try to remove line 186 and 189 and see if this works for you and I'll think about the edge case.

**Comment by michelwi** [comment]
Yes, changing the above lines to 
```
argv = sys.argv
del argv[argv.index('--redirect_output')]
```
Solves my problem. 
(Should we maybe copy the argv instead? 🤔 )

**Comment by critias** [comment]
I couldn't come up with any good reason why `argv = sys.argv[sys.argv.index(gs.CMD_WORKER):]` is used at this point. I think it's some left over code. Could you just push your fix or create an PR?
 
I think it doesn't matter if argv is changed at this point since a new process is spawned directly afterwards.
