### ISSUE TITLE
Path creator can be string or not?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#93]
https://github.com/rwth-i6/sisyphus/blob/ab073d37426b25aef65b89794065e9be3a834ee8/sisyphus/job_path.py#L67

https://github.com/rwth-i6/sisyphus/blob/ab073d37426b25aef65b89794065e9be3a834ee8/sisyphus/job_path.py#L109

https://github.com/rwth-i6/sisyphus/blob/ab073d37426b25aef65b89794065e9be3a834ee8/sisyphus/job_path.py#L153

But:

https://github.com/rwth-i6/sisyphus/blob/ab073d37426b25aef65b89794065e9be3a834ee8/sisyphus/job_path.py#L168

https://github.com/rwth-i6/sisyphus/blob/ab073d37426b25aef65b89794065e9be3a834ee8/sisyphus/job_path.py#L88

https://github.com/rwth-i6/sisyphus/blob/ab073d37426b25aef65b89794065e9be3a834ee8/sisyphus/job_path.py#L138

If there is really some case where this can happen (which avoids the `__init__`?) I think this should be better documented in the code with some comment.

**Comment by critias** [comment]
This code is a left over from the time when jobs could not be pickled. These checks are now removed: https://github.com/rwth-i6/sisyphus/commit/0eaaf3733791992ac4516c002be44825ed0f9bc3
